#! DATASET
generate_data: False # Generate and save data to pickle
downstream_task: age_group # age_group or sex (no impact on internal logic)
train_split: 0.7
val_split: 0.15
test_split: 0.15
sequence_length: 20
path_pickle_dataset: /mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/SwiFT/src/data/pickle_dataset
csv_path_adni: /mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/SwiFT/src/data/paths_dataset_adni.csv
csv_path_pain: /mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/SwiFT/src/data/paths_dataset_pain.csv

#! Best models
best_swin_age_group: /mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/SwiFT/results/2025-06-27_08-29-36/model-e28.pth # 93.3% val accuracy
best_swin_sex: /mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/SwiFT/results/2025-06-27_10-43-26/model-e9.pth # 93% val accuracy
best_swin_AD:  /mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/SwiFT/results/2025-07-04_09-40-42/model-e24.pth # 93% val accuracy
best_swin_4targets: /mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/SwiFT/results/2025-07-03_17-33-53/model-e14.pth
best_CLIP:  /mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/SwiFT/results/2025-07-02_15-44-05/model-e26.pth

#! TRAINING
seed: 42
num_workers: 16

epochs: 75
batch_size: 8
eval_batch_size: 1
learning_rate: 0.00001
dropout: 0.5
weight_decay: 0.03

#! SWIN (swin4d_ver7) config
img_size: [112, 112, 112, 20] # [96, 96, 96, 20]
in_chans: 1
embed_dim: 36
window_size: [4, 4, 4, 4]
first_window_size: [4, 4, 4, 4]
patch_size: [7, 7, 7, 1] # [6, 6, 6, 1] 
depths: [2, 2, 6, 2]
num_heads: [3, 6, 12, 24]
c_multiplier: 2
last_layer_full_MSA: False
n_stages: 4
num_classes: 2 # number of target classes

#! SWIN CLIP
text_embedding: 2
image_embedding: 46080
projection_dim: 256

#! Visualization
map_task: age_group # for maps and gradients
map_method: umap # for viz_maps